-- Agregar columna video_url a htb_machines
ALTER TABLE htb_machines ADD COLUMN IF NOT EXISTS video_url TEXT;

-- Crear tabla certifications
CREATE TABLE IF NOT EXISTS certifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Crear tabla machine_certifications
CREATE TABLE IF NOT EXISTS machine_certifications (
  machine_id BIGINT REFERENCES htb_machines(id) ON DELETE CASCADE,
  certification_id BIGINT REFERENCES certifications(id) ON DELETE CASCADE,
  PRIMARY KEY (machine_id, certification_id)
);

-- Índices para rendimiento
CREATE INDEX IF NOT EXISTS idx_machine_certifications_machine_id ON machine_certifications(machine_id);
CREATE INDEX IF NOT EXISTS idx_machine_certifications_certification_id ON machine_certifications(certification_id);
